specVersion: "0.0.1"
description: "This subquery indexes historic staking data for validators and rank them"
repository: "https://github.com/ashikmeerankutty/staking-subquery"

schema: "./schema.graphql"

network:
  endpoint: "wss://polkadot.api.onfinality.io/public-ws"

dataSources:
  - name: runtime
    kind: substrate/Runtime
    startBlock: 8000000
    mapping:
      handlers:
        - handler: handleValidatorAddress
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession
        - handler: handleEraSlashes
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession
        - handler: handleCouncilVotes
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession
        - handler: handleReferendums
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession
        - handler: handleProposals
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession
